openapi: 3.1.0
info:
  version: v1
  title: ECHO Hub Virtual Card Processing API
  
  description: >-
    API Endpoints for the ECHO VCP clients.
     

           SandBox url: https://sandbox.echohealthincapi.com/
           Production Url : https://api.echohealthincapi.com/
    
     
       # Authentication

       Authentication is a process by which a system verifies the identity of a
       user accessing this API.       
    
     
    
  contact:
    name: ECHO Health Inc.
    email: Echo.Hub@echohealthinc.com
servers:
  - url: https://sandbox.echohealthincapi.com
  - url: https://api.echohealthincapi.com    
        
  
security:
  - x-ApiKey: []
  - x-ClientKey: []
paths:
  #Authorization
  /api/v1/gettoken:
    $ref: paths/api@v1@gettoken.yaml
  #VCP  
  /api/VCP/V1/CardActivity:
    $ref: paths/VCP/api@VCP@V1@CardActivity.yaml
  /api/VCP/V1/CardCancel:
    $ref: paths/VCP/api@VCP@V1@CardCancel.yaml
      
components:
  securitySchemes:
    x-ApiKey:
      type: apiKey
      name: x-ApiKey
      description: The API key.
      in: header
    x-ClientKey:
      type: apiKey
      description: The client key.
      name: x-ClientKey
      in: header
    ApiKeyAuth:
      type: apiKey
      name: x-Authorization
      in: header
      description: Requests should pass an api_key header.  
    

